name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake --preset windows-ninja-debug

      - name: Build
        run: cmake --build --preset windows-ninja-debug --parallel

      - name: Test
        run: ctest --preset windows-ninja-debug --timeout 300
